Linux/MacOS support
RT-Thread/env pull request #185
Opened 2022-10-22 01:53 UTC by tangzz98

menuconfig在Linux/MacOS可以使用了

2022-10-22 04:33 UTC, mysterywolf commented
感谢提交PR， @Guozhanxin 郭老师请review一下

2022-10-22 04:36 UTC, mysterywolf requested changes

2022-10-22 04:36 UTC, mysterywolf commented on menuconfig
> +python ~/.env/tools/scripts/env.py menuconfig $*
这个地方你是使用python2.7跑的还是python3跑的。
目前env虽然是python3兼容的，但是我不太清楚是否python3能跑起来。
保险一点可以写 python2.7 ~/.env

或者 python 3 ~/ .env 

指定一下版本

2022-10-22 04:48 UTC, tangzz98 commented on menuconfig
> +python ~/.env/tools/scripts/env.py menuconfig $*
2.7和3都可以跑

2022-10-22 04:51 UTC, mysterywolf commented on menuconfig
> +python ~/.env/tools/scripts/env.py menuconfig $*
OK

2022-10-23 15:56 UTC, mysterywolf approved these changes

2022-10-25 20:08 UTC, mysterywolf commented
wsl2测试通过

2022-10-26 23:53 UTC, mysterywolf commented on env.py
> +        rtt_root = os.path.join(bsp_root, '..', '..')
这块可能不一定是向上反两级是rt-thread根目录，有可能是三级。靠这种方法可能不可靠。

2022-10-26 23:54 UTC, mysterywolf commented on env.py
> +        rtt_root = os.path.join(bsp_root, '..', '..')
这块可以问问熊大或者郭老师有没有什么更好的方法

2022-10-26 23:59 UTC, mysterywolf commented on env.py
> +        rtt_root = os.path.join(bsp_root, '..', '..')
RTT_ROOT 在什么情况下会缺失？

2022-10-27 03:31 UTC, tangzz98 commented on env.py
> +        rtt_root = os.path.join(bsp_root, '..', '..')
我在macos跑一直是缺失的

2022-10-28 17:08 UTC, merged

2022-10-28 17:08 UTC, mysterywolf commented
先合并  有问题再提😄